export const PRODUCT_CATEGORIE_REQUEST = 'PRODUCT_CATEGORIE_REQUEST';
export const PRODUCT_CATEGORIE_SUCCESS = 'PRODUCT_CATEGORIE_SUCCESS';
export const PRODUCT_CATEGORIE_ERROR = 'PRODUCT_CATEGORIE_ERROR';