export const PRODUCT_CATEGORIE_REQUEST = 'PRODUCT_CATEGORIE_REQUEST';
export const PRODUCT_CATEGORIE_SUCCESS = 'PRODUCT_CATEGORIE_SUCCESS';
export const PRODUCT_CATEGORIE_ERROR = 'PRODUCT_CATEGORIE_ERROR';
export const SORT_ASC = "SORT_ASC"
export const SORT_DESC = "SORT_DESC"
export const SORT_NEW = "SORT_NEW"
export const SORT_BY_PRICE_1_10 = 'SORT_BY_PRICE_1_10'
export const SORT_BY_PRICE_10_100 = 'SORT_BY_PRICE_10_100'
export const SORT_BY_PRICE_100_1000 = 'SORT_BY_PRICE_100_1000'

