export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';
export const GET_TOTAL_ITEMS = 'GET_TOTAL_ITEMS';
